// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int32            `json:"id"`
	UserID      pgtype.Int4      `json:"user_id"`
	Action      string           `json:"action"`
	MediaItemID pgtype.Int4      `json:"media_item_id"`
	MediaTitle  pgtype.Text      `json:"media_title"`
	MediaType   pgtype.Text      `json:"media_type"`
	Details     []byte           `json:"details"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type MediaItem struct {
	ID                 int32            `json:"id"`
	Title              string           `json:"title"`
	Type               string           `json:"type"`
	TmdbID             pgtype.Int4      `json:"tmdb_id"`
	TvdbID             pgtype.Int4      `json:"tvdb_id"`
	SonarrID           pgtype.Int4      `json:"sonarr_id"`
	RadarrID           pgtype.Int4      `json:"radarr_id"`
	OverseerrRequestID pgtype.Int4      `json:"overseerr_request_id"`
	RequestedByUserID  pgtype.Int4      `json:"requested_by_user_id"`
	FilePath           pgtype.Text      `json:"file_path"`
	FileSize           pgtype.Int8      `json:"file_size"`
	AddedDate          pgtype.Timestamp `json:"added_date"`
	LastSyncedAt       pgtype.Timestamp `json:"last_synced_at"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type SeedingOverride struct {
	ID                    int32            `json:"id"`
	TrackerID             pgtype.Int4      `json:"tracker_id"`
	TrackerName           pgtype.Text      `json:"tracker_name"`
	MinSeedingTimeSeconds pgtype.Int8      `json:"min_seeding_time_seconds"`
	MinSeedingRatio       pgtype.Numeric   `json:"min_seeding_ratio"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type Setting struct {
	Key       string           `json:"key"`
	Value     pgtype.Text      `json:"value"`
	Type      pgtype.Text      `json:"type"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type TautulliHistory struct {
	ID            int32            `json:"id"`
	MediaItemID   pgtype.Int4      `json:"media_item_id"`
	UserID        pgtype.Int4      `json:"user_id"`
	LastWatchedAt pgtype.Timestamp `json:"last_watched_at"`
	PlayCount     pgtype.Int4      `json:"play_count"`
	LastSyncedAt  pgtype.Timestamp `json:"last_synced_at"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Torrent struct {
	ID                     int32            `json:"id"`
	MediaItemID            pgtype.Int4      `json:"media_item_id"`
	Hash                   string           `json:"hash"`
	TrackerID              pgtype.Int4      `json:"tracker_id"`
	TrackerName            pgtype.Text      `json:"tracker_name"`
	TrackerType            pgtype.Text      `json:"tracker_type"`
	AddedDate              pgtype.Timestamp `json:"added_date"`
	SeedingTimeSeconds     pgtype.Int8      `json:"seeding_time_seconds"`
	UploadBytes            pgtype.Int8      `json:"upload_bytes"`
	DownloadBytes          pgtype.Int8      `json:"download_bytes"`
	Ratio                  pgtype.Numeric   `json:"ratio"`
	SeedingRequiredSeconds pgtype.Int8      `json:"seeding_required_seconds"`
	SeedingRequiredRatio   pgtype.Numeric   `json:"seeding_required_ratio"`
	IsSeeding              pgtype.Bool      `json:"is_seeding"`
	LastSyncedAt           pgtype.Timestamp `json:"last_synced_at"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID           int32            `json:"id"`
	Username     string           `json:"username"`
	Email        pgtype.Text      `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	PlexID       pgtype.Int4      `json:"plex_id"`
	PlexUsername pgtype.Text      `json:"plex_username"`
	IsAdmin      pgtype.Bool      `json:"is_admin"`
	IsActive     pgtype.Bool      `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
